_target_: ddpm_pytorch.model.classifier_free_ddpm.GaussianDDPMClassifierFreeGuidance
denoiser_module:
  _target_: ddpm_pytorch.model.unet.UNetTimeStepClassConditioned
  channels: [3, 128, 256, 256, 384]
  kernel_sizes: [3, 3, 3, 3]
  strides: [1, 1, 1, 1]
  paddings: [1, 1, 1, 1]
  p_dropouts: [0.1, 0.1, 0.1, 0.1]
  time_embed_size: 100  #did not found this hp on the paper
  downsample: true
  num_classes: ${dataset.num_classes}
T: ${noise_steps}
width: ${dataset.width}
height: ${dataset.height}
logging_freq: 1_000
input_channels: ${dataset.channels}
num_classes: ${dataset.num_classes}
v: 0.2