defaults:
  - model: unet_paper
  - scheduler: cosine
  - dataset: mnist
  - optional model_dataset: ${model}-${dataset}
  - optional model_scheduler: ${model}-${scheduler}

batch_size: 128
noise_steps: 4_000
accelerator: null
devices: null
gradient_clip_val: 0.0
gradient_clip_algorithm: norm
ema: true
ema_decay: 0.99

hydra:
  run:
    dir: saved_models/${now:%Y_%m_%d_%H_%M_%S}