defaults:
  - model: unet_paper
  - scheduler: cosine
  - dataset: mnist
  - optional model_dataset: ${model}-${dataset}
  - optional model_scheduler: ${model}-${scheduler}

batch_size: 128
noise_steps: 4_000  # T
accelerator: null
devices: null
gradient_clip_val: 0.0  # gradient clip value - set to 0.0 to disable
gradient_clip_algorithm: norm
ema: true  # exponential moving average
ema_decay: 0.99  # exponential moving average decay rate
early_stop: true  # stop training if the validation loss does not improve for patience epochs
patience: 10  # early stopping patience; set to -1 to disable
min_delta: 0.0  # minimum change in the monitored quantity to qualify as an improvement, i.e. an absolute change of less than min_delta, will count as no improvement.
ckpt: null  # path to checkpoint

hydra:
  run:
    dir: saved_models/${now:%Y_%m_%d_%H_%M_%S}